import Navbar from './Navbar'
import Footer from './Footer'

const sections = [
  {
    title: "1. General",
    items: [
      "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
      "This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Powerfiling.in.",
      'The domain name www.Powerfiling.com ("Website"), is owned and operated by BMS Tax Consultancy Services ("Firm"), a Partnership firm incorporated under the provisions of the Indian Partnership Act 1932, having its registered office at 96 Vipra Vihar, Sawai Gaitor, Near Shani Mandir, Malviya Nagar, Jaipur-302017, Rajasthan.',
      'For the purpose of this Privacy Policy ("Policy"), wherever the context so requires: (i) The term "You" & "User" shall mean any legal person or entity accessing or using the services provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872; (ii) The terms "We", "Us" & "Our" shall mean the Website and/or the Firm, as the context so requires; (iii) The terms "Party" & "Parties" shall respectively be used to refer to the User and the Firm individually and collectively, as the context so requires.',
      "The headings of each section in this Policy are only for the purpose of organizing the various provisions under this Policy in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.",
      "The use of the Website by the User is solely governed by this Policy as well as the Terms of Use of the Website (available at www.Powerfiling.com), and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User's unequivocal acceptance of this Policy and the aforementioned Terms.",
      "The User unequivocally agrees that this Policy and the aforementioned Terms constitute a legally binding agreement between the User and the Firm, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website.",
      "The Parties expressly agree that the Firm retains the sole and exclusive right to amend or modify the Policy and the aforementioned Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the Policy and Terms, and stay updated on their provisions and requirements.",
    ],
  },
  {
    title: "2. Collection of Personal and Other Information",
    items: [
      "The User expressly agrees and acknowledges that the firm collects and stores the User's personal information, which is provided by the User from time to time on the Website, including but not limited to the User's username, passwords, email address, name, address, age, date of birth, sex, nationality, shopping preferences, browsing history, etc., as well as any images or other information uploaded/published by the User on the Website.",
      "The User is aware that the firm/Website may automatically track certain information about the User based upon the User's IP address and the User's behaviour on the Website, and the User expressly consents to the same. This information is used to do internal research on user demographics, interests, and behaviour.",
      "If the User chooses to purchase products/services from the Website, the User consents to allowing the firm/Website to collect information about the User's buying behaviour and trends.",
      "If the User chooses to post messages/reviews/feedback anywhere on the Website, the User is aware that any and all such information provided/uploaded will be collected and stored by the firm indefinitely, and that such retained information may be used to resolve disputes, provide customer support, troubleshoot problems, etc.",
      "The User is aware that any and all information pertaining to the User collected by the firm, whether or not directly provided by the User, including but not limited to personal correspondence such as emails or letters, feedback from other users or third parties, may be collected and compiled by the firm/Website into a file/folder specifically created for the User.",
      "The User is aware that while he/she can browse some sections of the Website without being a registered user, certain activities (such as placing an order) require the User to provide valid personal information to the firm/Website for the purpose of registration.",
      "The User is aware that the firm/Website may occasionally request the User to complete optional online surveys requiring contact information and demographic information (like zip code, age, income bracket, sex, etc.) to customise the Website for the benefit of the User.",
      "The User is further aware that the firm/Website may occasionally request the User to write reviews for products/services purchased/availed of by the User from the Website, and the User hereby expressly authorises the firm/Website to publish any and all such reviews along with the User's name and certain contact details.",
      "Nothing contained herein shall be deemed to compel the Website/firm to store, upload, publish, or display in any manner content/reviews/surveys/feedback submitted by the User, and the User hereby expressly authorises the Website/firm to remove from the Website any such content without cause.",
      "As you access and use our services, we collect certain information from you, including but not limited to phone number, email address, device make-details, and IP address. By accessing and using our services, you expressly consent to the sharing and disclosure of your information so collected, with our third-party service providers, business partners, and agents.",
    ],
  },
  {
    title: "3. Cookies",
    items: [
      "The User is aware that a 'Cookie' is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular browser. Cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User's login identification, password, etc. The User is aware that the Website places both permanent and temporary cookies in the User's computer's hard drive and web browser, and does hereby expressly consent to the same.",
      "The User is further aware that the Website uses data collection devices such as cookies on certain pages of the Website to help analyse web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website are only available through the use of such cookies.",
      "Additionally, the User is aware that he/she might encounter 'cookies' or other similar devices on certain pages of the Website that are placed by third parties or affiliates of the Firm/Website. The Firm/Website does not control the use of such cookies/other devices by third parties and is in no way responsible for the same.",
      "A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual by gathering and remembering information about your preferences.",
      "Overall, cookies help us provide you with a better website by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.",
      "You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.",
    ],
  },
  {
    title: "Links to Other Websites",
    body: "Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.",
  },
  {
    title: "Controlling Your Personal Information",
    items: [
      "You may choose to restrict the collection or use of your personal information. We use information for internal record keeping and to improve our products and services.",
      "We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.",
      "From time to time, we may also use your information to contact you for market research purposes by email, phone, fax or mail. We may use the information to customize the website according to your interests.",
      "We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so.",
      "If you believe that any information we are holding on you is incorrect or incomplete, please write to or email us as soon as possible. We will promptly correct any information found to be incorrect.",
    ],
  },
  {
    title: "4. Divulging / Sharing of Personal Information",
    items: [
      "The User is aware that the Website/Firm may share the User's personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website's services; and to facilitate joint or co-branded services.",
      "The User is aware that the Website/Firm may disclose personal information if required to do so by law or if the Website/Firm in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes.",
      "The User is further aware that the Website/Firm and its affiliates may share/sell some or all of the User's personal information with other business entities should the Firm/Website plan to merge with, or be acquired by such business entity, or in the event of re-organization, amalgamation, or restructuring of the Company's business.",
    ],
  },
  {
    title: "5. Security",
    body: "Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties. The User's credit and debit card information is not received, stored by or retained by the Firm/Website in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.",
  },
  {
    title: "6. Third Party Advertisements / Promotions",
    body: "The User is aware that the Firm/Website uses third-party advertising companies to serve ads to the users of the Website. These companies may use information relating to the User's visits to the Website and other websites in order to provide customised advertisements to the User. Furthermore, the Website may contain links to other websites that may collect personally identifiable information about the User. The Firm/Website is not responsible for the privacy practices or the content of any of the aforementioned linked websites.",
  },
  {
    title: "7. User's Consent",
    body: "By using the Website and/or by providing information to the Firm through the Website, the User consents to the collection and use of the information disclosed by the User on the Website in accordance with this Policy, including but not limited to the User's consent to the Firm/Website sharing/divulging the User's information as per the terms contained hereinabove in Section 4 of the Policy.",
  },
  {
    title: "8. Grievance Officer",
    body: "In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:",
    grievance: {
      name: "Shubham Chordia",
      email: "Shubhambeing12@gmail.com",
    },
  },
  {
    title: "9. Dispute Resolution and Jurisdiction",
    items: [
      'It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of this Policy and any disputes arising here from will be resolved through a two-step Alternate Dispute Resolution ("ADR") mechanism.',
      "Mediation: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration.",
      "Arbitration: In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the firm, and the award passed by such sole arbitrator will be valid and binding on both Parties. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Jaipur in the state of Rajasthan, India.",
      "The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at Jaipur, Rajasthan, shall have exclusive jurisdiction over any disputes arising between the Parties.",
    ],
  },
]

const Security = () => {
  return (
    <>
      <Navbar />

      <main className="bg-slate-50 min-h-screen">

        {/* Hero Banner */}
        <div className="bg-gradient-to-br from-slate-900 to-blue-900 text-white py-14 px-4">
          <div className="max-w-4xl mx-auto text-center">
            <span className="inline-block bg-blue-500/20 border border-blue-400/30 text-blue-300 text-xs font-semibold px-3 py-1 rounded-full mb-4 uppercase tracking-wider">
              Legal
            </span>
            <h1 className="text-3xl sm:text-4xl font-bold mb-3">Security &amp; Terms of Use</h1>
            {/* <p className="text-slate-300 text-sm">Last Updated: January 1, 2025</p> */}
          </div>
        </div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 space-y-6">

          {sections.map((section, idx) => (
            <div key={idx} className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8">
              <h2 className="text-lg font-bold text-slate-900 pb-3 mb-5 border-b border-slate-100">
                {section.title}
              </h2>

              {section.body && (
                <p className="text-slate-700 text-sm leading-relaxed">{section.body}</p>
              )}

              {section.items && (
                <ul className="space-y-3">
                  {section.items.map((item, i) => (
                    <li key={i} className="flex gap-3 text-slate-700 text-sm leading-relaxed">
                      <span className="mt-1.5 w-2 h-2 rounded-full bg-blue-400 flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {section.grievance && (
                <div className="mt-4 bg-slate-50 rounded-xl border border-slate-200 p-5">
                  <p className="text-sm font-semibold text-slate-800 uppercase tracking-wider mb-3">Grievance Officer</p>
                  <div className="grid sm:grid-cols-2 gap-3 text-sm text-slate-700">
                    <div>
                      <span className="font-medium text-slate-500 block mb-0.5">Name</span>
                      {section.grievance.name}
                    </div>
                    <div>
                      <span className="font-medium text-slate-500 block mb-0.5">Email</span>
                      <a href={`mailto:${section.grievance.email}`} className="text-blue-600 hover:underline">
                        {section.grievance.email}
                      </a>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}

        </div>
      </main>

      <Footer />
    </>
  )
}

export default Security
